import homeBanner1 from "@/assets/images/bgImages/homeBanner1.png";
import industryOil from '@/assets/images/home/industry-oil.png'
import industryMining from '@/assets/images/home/industry-mining.png'
import sapImplementation from '@/assets/images/home/sap-implementation.png'
import techSvg from '../assets/images/icons/tech.svg'
import cloudNetworkingSvg from '../assets/images/icons/cloud-networking.svg'

export const slidesData = [
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
]

export const industryDetails = [
    {
        name: 'Oil and Gas',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/oil-and-gas',
        image: industryOil,
    },
    {
        name: 'Mining',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/metal-and-mining',
        image: industryMining,
    },
    {
        name: 'Agriculture',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/agriculture',
        image: industryOil,
    },
    {
        name: 'Chemicals',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/chemical',
        image: industryMining,
    },
]

export const sapServicesDetails = [
    {
        name: 'SAP Implementation',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'SAP Support',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'SAP Rollout',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Data Migration',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Data Upgrade',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Advisory',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
]

export const whyChooseUsData = [
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'HiTech Service',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
    {
        name: 'Certified Force',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
]