import homeBanner1 from "@/assets/images/bgImages/homeBanner1.png";
import industryOil from '@/assets/images/home/industry-oil.png'
import industryMining from '@/assets/images/home/industry-mining.png'
import sapImplementation from '@/assets/images/home/sap-implementation.png'
import reviewPerson from '@/assets/images/home/review-person.png'
import techSvg from '../assets/images/icons/tech.svg'
import cloudNetworkingSvg from '../assets/images/icons/cloud-networking.svg'
import partner1 from '@/assets/images/partners/1.png'
import partner2 from '@/assets/images/partners/2.png'
import partner3 from '@/assets/images/partners/3.png'
import partner4 from '@/assets/images/partners/4.png'
import partner5 from '@/assets/images/partners/5.png'
import partner6 from '@/assets/images/partners/6.png'
import partner7 from '@/assets/images/partners/7.png'
import partner8 from '@/assets/images/partners/8.png'
import partner9 from '@/assets/images/partners/9.png'
import partner10 from '@/assets/images/partners/10.png'
import partner11 from '@/assets/images/partners/11.png'
import partner12 from '@/assets/images/partners/12.png'
import partner13 from '@/assets/images/partners/13.png'
import partner14 from '@/assets/images/partners/14.png'

export const slidesData = [
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
    {
        heading: 'Upstream to Downstream, our SAP supply chain solutions for you',
        para: "Whether it's optimizing exploration and production operations , our SAP-powered supply chain solutions delivercontrol, and agility.",
        image: homeBanner1,
        link: '/about-us',
        cta: '/contact-us',
    },
]

export const industryDetails = [
    {
        name: 'Oil and Gas',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/oil-and-gas',
        image: industryOil,
    },
    {
        name: 'Mining',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/metal-and-mining',
        image: industryMining,
    },
    {
        name: 'Agriculture',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/agriculture',
        image: industryOil,
    },
    {
        name: 'Chemicals',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        link: '/industries/chemical',
        image: industryMining,
    },
]

export const sapServicesDetails = [
    {
        name: 'SAP Implementation',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'SAP Support',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'SAP Rollout',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Data Migration',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Data Upgrade',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
    {
        name: 'Advisory',
        description: 'Complete development and implementation of IS-Oil & Gas module.',
        image: sapImplementation,
    },
]

export const whyChooseUsData = [
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'HiTech Service',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
    {
        name: 'Certified Force',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: cloudNetworkingSvg,
    },
    {
        name: 'Cloud Driven Tech',
        description: 'Our teams create native and cross-platform IoT-driven applications that open up space for smart access and analysis of data generated by in this way providing businesses with the ability to get a better understanding of their custome.',
        image: techSvg,
    },
]

export const partnersDetails = [
    {
        name: 'partner1',
        image: partner1,
    },
    {
        name: 'partner2',
        image: partner2,
    },
    {
        name: 'partner3',
        image: partner3,
    },
    {
        name: 'partner4',
        image: partner4,
    },
    {
        name: 'partner5',
        image: partner5,
    },
    {
        name: 'partner6',
        image: partner6,
    },
    {
        name: 'partner7',
        image: partner7,
    },
    {
        name: 'partner8',
        image: partner8,
    },
    {
        name: 'partner9',
        image: partner9,
    },
    {
        name: 'partner10',
        image: partner10,
    },
    {
        name: 'partner11',
        image: partner11,
    },
    {
        name: 'partner12',
        image: partner12,
    },
    {
        name: 'partner13',
        image: partner13,
    },
    {
        name: 'partner14',
        image: partner14,
    },
]

export const reviewData = [
    {
        name: 'Jonhathan Wick',
        position: 'Director, Table.inc',
        review: "Finsweet has been a wonderful partner to work with. I have been a customer now for the past few months now and I have had nothing but positive experiences! and these positives lead to our growth  but positive experiences! and these positives lead to our growth but positive experiences! and these positives lead to our growth",
        image: reviewPerson,
    },
    {
        name: 'Jonhathan Wick',
        position: 'Director, Table.inc',
        review: "Finsweet has been a wonderful partner to work with. I have been a customer now for the past few months now and I have had nothing but positive experiences! and these positives lead to our growth  but positive experiences! and these positives lead to our growth but positive experiences! and these positives lead to our growth",
        image: reviewPerson,
    },
    {
        name: 'Jonhathan Wick',
        position: 'Director, Table.inc',
        review: "Finsweet has been a wonderful partner to work with. I have been a customer now for the past few months now and I have had nothing but positive experiences! and these positives lead to our growth  but positive experiences! and these positives lead to our growth but positive experiences! and these positives lead to our growth",
        image: reviewPerson,
    },
]